follow rime/librime pr 806, breaking change [WIP]
rime/weasel pull request #1098
Opened 2024-02-06 15:27 UTC by fxliang

build librime in ci
remove debug stuff from release ci

2024-02-06 15:37 UTC, lotem commented on github.install.bat
> -setlocal
別刪吶。
以後搞回來。編譯快啊。

我想要不要整理一下腳本，支持比較快地在兩種構建方式中間切換，比如只需做單行修改的commit就能切換到另一套。

2024-02-06 15:43 UTC, lotem commented on .github/workflows/commit-ci.yml
> +          # load plugins
其實有腳本的。

設置環境變量 `RIME_PLUGINS=xxx/librime-xxxx yyy-librime/yyyy`

```cmd
librime\action-install-plugins-windows.bat
```

腳本把目錄名縮短了。我不記得這一點是不是重要。

2024-02-06 15:46 UTC, lotem commented on .github/workflows/commit-ci.yml
> -      - name: Copy Rime files
別刪，加一個條件 `if: ${{ ! build_librime }}` 根據 build_librime 選項分別走 Copy Rime files 和 Build librime

2024-02-06 15:47 UTC, fxliang commented on github.install.bat
> -setlocal
奇怪的是我原来分支ci过了然后删减点commit 数就似乎出问题了？或者你直接在上面改也行

2024-02-06 16:51 UTC, fxliang commented on .github/workflows/commit-ci.yml
> -      - name: Copy Rime files
可能更好的办法是cache构建产物？当然这个我没经验

2024-02-07 07:24 UTC, fxliang commented on .github/workflows/commit-ci.yml
> +          # load plugins
改了，用librime的脚本处理librime插件初始化

2024-02-07 11:59 UTC, fxliang commented on .github/workflows/commit-ci.yml
> -      - name: Copy Rime files
> 別刪，加一個條件 `if: ${{ ! build_librime }}` 根據 build_librime 選項分別走 Copy Rime files 和 Build librime

改了，commit 用librime nightly build, release 重新构建submodule的librime

2024-02-07 12:02 UTC, lotem commented on .github/workflows/release-ci.yml
> +          #.\build.bat opencc
想不起來原來爲啥有這一行。你知道嗎？

2024-02-07 12:02 UTC, lotem approved these changes
好好好

2024-02-07 12:08 UTC, fxliang commented on .github/workflows/release-ci.yml
> +          #.\build.bat opencc
哦，build librime之后 少了，应该移上去

2024-02-07 12:21 UTC, lotem requested changes

2024-02-07 12:21 UTC, lotem commented on .github/workflows/commit-ci.yml
>            rime_plugins: hchunhui/librime-lua lotem/librime-octagram rime/librime-predict
分不分大小寫？ 腳本裏讀的是 `RIME_PLUGINS`

2024-02-07 12:46 UTC, fxliang commented on .github/workflows/commit-ci.yml
>            rime_plugins: hchunhui/librime-lua lotem/librime-octagram rime/librime-predict
https://github.com/rime/weasel/actions/runs/7811313753/job/21306180985
似乎不分

2024-02-08 12:40 UTC, lotem commented
先別改了。我又改了很多，等我把 `breaking` 分支合併了你再 rebase 吧。

2024-02-09 15:08 UTC, fxliang commented
> 先別改了。我又改了很多，等我把 `breaking` 分支合併了你再 rebase 吧。

似乎这个pr可以关闭了

2024-02-18 06:40 UTC, closed without merging